services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    restart: always
    networks:
      - backend
    ports: 
      - "8000:8000"
    command: "sh /app/web.entrypoint.sh"
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
    - postgres

networks:
  backend:
    driver: bridge