services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
    ports:
      - "5432:5432"
    env_file:
    - ../.env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

volumes:
  postgres_data:
  
networks:
  backend:
    driver: bridge