services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    networks:
      - backend
    ports:
      - "5432:5432"
    env_file:
    - ../.env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

networks:
  backend:
    driver: bridge